### ISSUE TITLE
Color mode

### ISSUE THREAD

**Issue by whoem** [GunshipPenguin/open_flood#16] opened 2016-03-17 10:39 UTC
Please please give us back the original color mode. The new colors look bright and neat, though. But after a few rounds it hurts my eyes. The original colors were not that beautiful, but they had sharp transitions to each other. At least let the player chose which color mode to pick. Would be a benefit for the game imho :D Great game!

**Comment by OvOwl** [comment] 2016-03-17 17:35
+1 for that.
I am actually red/green blind and the new colors make the game even harder. The new color blind option isn't really a good alternative since the old colors had enough contrast to be fun to while being possible. The gameplay had a huge shift through that change.
Maybe implementing the new colors as difficulty level would be a better way.

**Comment by GunshipPenguin** [comment] 2016-03-18 05:01
Duplicate of #12. 

I plan to add an option to revert back to the old color scheme in the next release as well as desaturate the current color scheme to make it easier on the eyes.

See my comments in the discussion in #12 for more info.

**Comment by GunshipPenguin** [comment] 2016-03-21 07:06
ed70b50b84a83d4fd4a863df7b53f46a773f2617 and c32013dfc331d4a05cff14b46aa672227e2db1d3

**Closed by GunshipPenguin** 2016-03-21 07:06 UTC

**Comment by omerule** [comment] 2016-03-25 07:28
Nice game, for me the orginale colours worked beter.
But i can't choose those Nice colours any more.
Is it possible to make it an option like "classic" mode?
Yours kindly
Roel 
The Netherlands

**Comment by OvOwl** [comment] 2016-03-25 08:17
You should update to 1.2.2 and have a look into the settings -> "Old Color Scheme".

btw. Thanks for that :+1:
